export const REGISTER = {
    REQUEST: 'REGISTER',
    SUCCESS: 'SUCCESSFULLY REGISTERED',
    ERROR: 'FAILED TO REGISTERED',
};
export const LOGIN = {
    REQUEST: 'LOGIN',
    SUCCESS: 'SUCCESSFULLY LOGGED IN',
    ERROR: 'FAILED TO LOGIN',
};
export const LOGOUT = {
    REQUEST: 'LOGOUT',
    SUCCESS: 'SUCCESSFULLY LOGGED OUT',
    ERROR: 'FAIED TO LOGOUT',
};
export const AUTH = {
    UPDATE_FIELD: 'UPDATE_FIELD_AUTH',
    CANCEL: 'CANCEL',
};
export const FETCH_DATA_TO_PRODUCT = 'FETCH_DATA_TO_PRODUCT';
export const FETCH_DATA_TO_PRODUCT_SEARCH = 'FETCH_DATA_TO_PRODUCT_SEARCH';

export const FETCH_DATA_TO_PRODUCT_FAILURE = 'FETCH_DATA_TO_PRODUCT_FAILURE';
export const POSTS = {
    REQUEST: 'REQUESTING',
    UPLOAD_SUCCEED: 'UPLOAD_POST_SUCCEED',
    UPLOAD_FAILED: 'UPLOAD_POST_FAILED',
    UPDATE_SUCCEED: 'UPDATE_POST_SUCCEED',
    UPDATE_FAILED: 'UPDATE_POST_FAILED',
    FETCH_DATA_SUCCEED: 'FETCH_DATA_SUCCEED',
    FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
    DISMISS_MESSAGE: 'REMOVE_MESSAGE',
    UPLOAD_CANCELED: 'UPLOAD_POST_CANCELED',
    UPDATE_CANCELED: 'UPDATE_POST_CANCELED',
};
export const MODELS = {
    REQUEST: 'REQUESTING',
    LOAD_MODEL_SUCCEED: 'LOAD_MODEL_SUCCEED',
    LOAD_MODEL_FAILED: 'LOAD_MODEL_FAILED',
};
export const BRANDS = {
    REQUEST: 'REQUESTING',
    LOAD_BRAND_SUCCEED: 'LOAD_BRAND_SUCCEED',
    LOAD_BRAND_FAILED: 'LOAD_BRAND_FAILED',
};
