export const REGISTER = {
    REQUEST: 'REGISTER',
    SUCCESS: 'SUCCESSFULLY REGISTERED',
    ERROR: 'FAILED TO REGISTERED',
};

export const LOGIN = {
    REQUEST: 'LOGIN',
    SUCCESS: 'SUCCESSFULLY LOGGED IN',
    ERROR: 'FAILED TO LOGIN',
};

export const LOGOUT = {
    REQUEST: 'LOGOUT',
    SUCCESS: 'SUCCESSFULLY LOGGED OUT',
    ERROR: 'FAIED TO LOGOUT',
};

export const AUTH = {
    UPDATE_FIELD: 'UPDATE_FIELD_AUTH',
    CANCEL: 'CANCEL',
};

export const PRODUCTS = {
    REQUEST: 'PRODUCT_REQUESTING',
    FETCH_LIST_POSTS_SUCCEED: 'FETCH_LIST_POSTS_SUCCEED',
    FETCH_LIST_POSTS_FAILURE: 'FETCH_LIST_POSTS_FAILURE',
    FETCH_LIST_POSTS_SEARCH_SUCCEED: 'FETCH_LIST_POSTS_SEARCH_SUCCEED',
    FETCH_LIST_POSTS_SEARCH_FAILURE: 'FETCH_LIST_POSTS_SEARCH_FAILURE',
};

export const POSTS = {
    CANCEL: 'CANCEL_HANDLING_POST',
    REQUEST: 'REQUESTING',
    UPLOAD_SUCCEED: 'UPLOAD_POST_SUCCEED',
    UPLOAD_FAILED: 'UPLOAD_POST_FAILED',
    UPDATE_SUCCEED: 'UPDATE_POST_SUCCEED',
    UPDATE_FAILED: 'UPDATE_POST_FAILED',
    FETCH_DATA_SUCCEED: 'FETCH_DATA_SUCCEED',
    FETCH_DATA_FAILED: 'FETCH_DATA_FAILED',
    DISMISS_MESSAGE: 'REMOVE_MESSAGE',
    LOCATION: 'CHANGE_LOCATION_IN_HANDLING_POST',
};

export const MODELS = {
    REQUEST: 'REQUESTING',
    LOAD_MODEL_SUCCEED: 'LOAD_MODEL_SUCCEED',
    LOAD_MODEL_FAILED: 'LOAD_MODEL_FAILED',
};

export const BRANDS = {
    REQUEST: 'REQUESTING',
    LOAD_BRAND_SUCCEED: 'LOAD_BRAND_SUCCEED',
    LOAD_BRAND_FAILED: 'LOAD_BRAND_FAILED',
};
