export const REGISTER = {
    REQUEST: 'REGISTER',
    SUCCESS: 'SUCCESSFULLY REGISTERED',
    ERROR: 'FAILED TO REGISTERED',
};
export const LOGIN = {
    REQUEST: 'LOGIN',
    SUCCESS: 'SUCCESSFULLY LOGGED IN',
    ERROR: 'FAILED TO LOGIN',
};
export const UPDATE_FIELD_AUTH = 'UPDATE_FIELD_AUTH';
export const MODAL_ON = 'SHOW THE MODAL';
export const MODAL_OFF = 'HIDE THE MODAL';
export const FETCH_DATA_TO_PRODUCT = 'FETCH_DATA_TO_PRODUCT';
export const FETCH_DATA_TO_PRODUCT_FAILURE = 'FETCH_DATA_TO_PRODUCT_FAILURE';
